name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04 # En kararlı sürümü kullanıyoruz

    steps:
      - uses: actions/checkout@v4

      # 1. Python ve Gerekli Araçları Kur
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 2. Buildozer ve Kütüphaneleri Yükle (Colab'daki gibi)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi-dev libltdl-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      # 3. APK'yı Pişir (Soru sormasın diye 'yes' komutuyla)
      - name: Build with Buildozer
        run: |
          yes | buildozer android debug

      # 4. APK'yı Sisteme Yükle
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
